name: EurekaMetrics
favicon: null
layout_spectrum: 0.51188
typography_spectrum: 0.51998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4779ba'
    - '#8ec448'
    - '#000000'
    - '#005555'
    - '#0000ff'
  brandStrength: 0.6998029877431691
  lightness: 0.46893080812878907
  saturation: 0.730929056648165
  rhythmicContrast: 0.25
purpose: []
